name: Java Selenium TestNG CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: "21"

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Build with Maven
      run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: surefire-reports
        path: target/surefire-reports

    - name: Upload Screenshots (if any)
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: test-output/screenshots
        if-no-files-found: ignore
